# rib application configuration
# Access configs using APP_CONFIG['setting']
# In seconds
# year    - 31536000
# 30 days - 2592000
# week    - 604800
# day     - 86400
# hour    - 3600

defaults: &defaults
  max_posts_in_discussion: 400
  max_discussions_in_board: 100
  prune_by_age: false
# max_discussions_age in seconds
  max_discussions_age: 604800
  max_content_size_mb: 4
  max_text_length: 2500
  max_title_length: 100
  application_name: 'rib'
# poll_interval in milliseconds
  poll_interval: 30000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults